"""add image_hash column to file_records

Revision ID: 7c230dca3ad9
Revises: 6a369834a0cd
Create Date: 2026-07-10 14:45:18.639832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c230dca3ad9'
down_revision: Union[str, Sequence[str], None] = '6a369834a0cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_records', sa.Column('image_hash', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file_records', 'image_hash')
    # ### end Alembic commands ###
