"""Initial schema

Revision ID: c7ba0e7dd19a
Revises: 
Create Date: 2026-07-10 13:08:59.279173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7ba0e7dd19a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('destination', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('triggered_by', sa.String(), nullable=False),
    sa.Column('dry_run_preview', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sources',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('roots', sa.JSON(), nullable=False),
    sa.Column('agent_key_hash', sa.String(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('file_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('relative_path', sa.String(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('mtime', sa.DateTime(), nullable=False),
    sa.Column('hash_sha256', sa.String(), nullable=False),
    sa.Column('scanned_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'relative_path', name='_source_id_relative_path_uc')
    )
    op.create_index('idx_file_records_hash', 'file_records', ['source_id', 'hash_sha256'], unique=False)
    op.create_index('idx_file_records_hash_sha256', 'file_records', ['hash_sha256'], unique=False)
    op.create_index('idx_file_records_path', 'file_records', ['source_id', 'relative_path'], unique=False)
    op.create_table('undo_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('action_id', sa.String(), nullable=False),
    sa.Column('backup_path', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('restored', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['action_id'], ['action_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('undo_records')
    op.drop_index('idx_file_records_path', table_name='file_records')
    op.drop_index('idx_file_records_hash_sha256', table_name='file_records')
    op.drop_index('idx_file_records_hash', table_name='file_records')
    op.drop_table('file_records')
    op.drop_table('sources')
    op.drop_table('action_records')
    # ### end Alembic commands ###
